In [2]:
import numpy as np

In [39]:
test = np.zeros((2,2,2,10))

In [40]:
test[:,0,0:2:2,:] = 1

In [41]:
print(test[:,0,:,:])

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [15]:
np.exp(5)

148.4131591025766

In [46]:
test[:,:,:,0:4:1]

array([[[[1., 1., 1., 1.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[1., 1., 1., 1.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])